name: istiqamah_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+6

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:

  flutter_localizations:
    sdk: flutter
  flutter_automation: ^2.0.0

  intl: ^0.17.0
  hijri: ^3.0.0
  webview_flutter: ^3.0.4

  provider:
  flutter_bloc: ^7.1.0
  flutter_phoenix: ^1.0.0

  timer_button: ^2.0.0

  #UI
  flutter_spinkit: ^5.1.0
  top_snackbar_flutter: ^2.1.1
  dots_indicator: ^2.1.0
  extended: ^0.1.10
  smooth_page_indicator: ^1.0.0+2

  # IMAGES
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  file_picker: ^5.0.0
  photo_view: ^0.14.0
  card_swiper: ^2.0.4

  # Base
  nb_utils: ^4.6.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^3.0.1

  # Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.5.1
  firebase_storage: ^10.3.3
  cloud_firestore: ^3.4.1
  firebase_phone_auth_handler: 1.0.6
  auth_with_firebase: ^0.0.25


  #device_info
  device_info_plus: ^4.0.1

  #send email
  flutter_email_sender: ^5.1.0

  #ss
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  image_gallery_saver: ^1.7.1

  #notification
  url_launcher: ^6.1.3
  awesome_notifications: ^0.6.21
  bottom_picker: ^1.8.0
  delayed_display: ^2.0.0

    #notification
  flutter_local_notifications: ^9.6.0
  flutter_local_notifications_linux: ^0.5.0+1
  flutter_local_notifications_platform_interface: ^5.0.0
  timezone: ^0.8.0
  clock: ^1.1.0
  flutter_native_timezone: ^2.0.0
  shimmer: ^2.0.0
  async: ^2.8.2

    #Etc
  country_code_picker: ^2.0.2
  flutter_datetime_picker: ^1.5.1
  country_list_pick: ^1.0.1+6
  numeric_keyboard: ^1.1.0


  #local storage
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15
  feature_discovery: ^0.14.1
  cool_alert: ^1.1.0
  flare_flutter: ^3.0.2
  vector_math: ^2.1.2
  cron: ^0.5.0
  package_info_plus: ^1.4.2

  flutter_background_service: ^2.1.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  floating_bottom_navigation_bar: ^1.5.2

  date_picker_timeline: ^1.2.3
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  rxdart: ^0.27.4

  external_app_launcher: ^3.0.0
  flutter_zoom_drawer: ^3.0.3

  #change package name
  change_app_package_name: ^1.1.0
  readmore: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/avatar/
    - assets/Logo As-sunnah_whitebg-02-02.png
    - assets/Logo As-Sunnah_Malay_WBG-03.png
