import 'package:flutter/material.dart';
import 'neat_and_clean_calendar_event.dart';

//
List<NeatCleanCalendarEvent> eventList() {
  //TODO EVENT LIST
  final eventList = [
    //sambutan dan perayaan
    NeatCleanCalendarEvent('Hari Raya Aidulfitri',
        color: Colors.purple[400],
        startTime: DateTime(2022, 5, 2),
        endTime: DateTime(2022, 5, 2),
        isAllDay: true),
    NeatCleanCalendarEvent('Hari Raya Aidiladha',
        color: Colors.purple[400],
        startTime: DateTime(2022, 7, 10),
        endTime: DateTime(2022, 7, 10),
        isAllDay: true),
    NeatCleanCalendarEvent('Maulidurasul',
        color: Colors.purple[400],
        startTime: DateTime(2022, 10, 9),
        endTime: DateTime(2022, 10, 9),
        isAllDay: true),
    NeatCleanCalendarEvent('Israk Mikraj',
        color: Colors.purple[400],
        startTime: DateTime(2022, 3, 1),
        endTime: DateTime(2022, 3, 1),
        isAllDay: true),
    NeatCleanCalendarEvent('Awal Ramadhan',
        color: Colors.purple[400],
        startTime: DateTime(2022, 4, 3),
        endTime: DateTime(2022, 4, 3),
        isAllDay: true),
    NeatCleanCalendarEvent('Nuzul Al-Quran',
        color: Colors.purple[400],
        startTime: DateTime(2022, 4, 19),
        endTime: DateTime(2022, 4, 19),
        isAllDay: true),

    //awal bulan
    NeatCleanCalendarEvent('1 Jamadil Akhir',
        color: Colors.orange[400],
        startTime: DateTime(2022, 1, 4),
        endTime: DateTime(2022, 1, 4),
        isAllDay: true),
    NeatCleanCalendarEvent('1 Rejab',
        color: Colors.orange[400],
        startTime: DateTime(2022, 2, 3),
        endTime: DateTime(2022, 2, 3),
        isAllDay: true),
    NeatCleanCalendarEvent('1 Syaaban',
        color: Colors.orange[400],
        startTime: DateTime(2022, 3, 4),
        endTime: DateTime(2022, 3, 4),
        isAllDay: true),
    // NeatCleanCalendarEvent('1 Ramadhan',
    //     color: Colors.orange[400],
    //     startTime: DateTime(2022, 4, 3),
    //     endTime: DateTime(2022, 4, 3),
    //     isAllDay: true),
    // NeatCleanCalendarEvent('1 Syawal',
    //     color: Colors.orange[400],
    //     startTime: DateTime(2022, 5, 2),
    //     endTime: DateTime(2022, 5, 2),
    //     isAllDay: true),
    NeatCleanCalendarEvent('1 Zulkaedah',
        color: Colors.orange[400],
        startTime: DateTime(2022, 6, 1),
        endTime: DateTime(2022, 6, 1),
        isAllDay: true),
    NeatCleanCalendarEvent('1 Zulhijjahh',
        color: Colors.orange[400],
        startTime: DateTime(2022, 7, 1),
        endTime: DateTime(2022, 7, 1),
        isAllDay: true),
    NeatCleanCalendarEvent('1 Muharram',
        color: Colors.orange[400],
        startTime: DateTime(2022, 7, 30),
        endTime: DateTime(2022, 7, 1),
        isAllDay: true),
    NeatCleanCalendarEvent('1 Safar',
        color: Colors.orange[400],
        startTime: DateTime(2022, 8, 29),
        endTime: DateTime(2022, 8, 29),
        isAllDay: true),
    NeatCleanCalendarEvent('1 Rabiulawal',
        color: Colors.orange[400],
        startTime: DateTime(2022, 9, 28),
        endTime: DateTime(2022, 9, 28),
        isAllDay: true),
    NeatCleanCalendarEvent('1 Rabiulakhir',
        color: Colors.orange[400],
        startTime: DateTime(2022, 10, 27),
        endTime: DateTime(2022, 10, 27),
        isAllDay: true),
    NeatCleanCalendarEvent('1 JamadilAwal',
        color: Colors.orange[400],
        startTime: DateTime(2022, 11, 26),
        endTime: DateTime(2022, 11, 26),
        isAllDay: true),
    NeatCleanCalendarEvent('1 JamadilAkhir',
        color: Colors.orange[400],
        startTime: DateTime(2022, 12, 25),
        endTime: DateTime(2022, 12, 25),
        isAllDay: true),

    //hari haram puasa
    NeatCleanCalendarEvent('10 Zulhijjah',
        color: Colors.red[900],
        description: 'Hari yang diharamkan berpuasa',
        startTime: DateTime(2022, 7, 10),
        endTime: DateTime(2022, 7, 10),
        isAllDay: true),
    NeatCleanCalendarEvent('Hari-hari Tasyrik',
        color: Colors.red[900],
        description: 'Hari yang diharamkan berpuasa',
        startTime: DateTime(2022, 7, 11),
        endTime: DateTime(2022, 7, 13),
        isAllDay: true),
    NeatCleanCalendarEvent('1 Syawal',
        color: Colors.red[900],
        description: 'Hari yang diharamkan berpuasa',
        startTime: DateTime(2022, 5, 2),
        endTime: DateTime(2022, 5, 2),
        isAllDay: true),

    //hari sunat puasa
    NeatCleanCalendarEvent('Puasa Hari Arafah',
        color: Colors.teal[400],
        description: 'Hari yang disunatkan berpuasa',
        startTime: DateTime(2022, 7, 9),
        endTime: DateTime(2022, 7, 9),
        isAllDay: true),
    NeatCleanCalendarEvent("Puasa Tasu'a",
        color: Colors.teal[400],
        description: 'Hari yang disunatkan berpuasa',
        startTime: DateTime(2022, 8, 7),
        endTime: DateTime(2022, 8, 7),
        isAllDay: true),
    NeatCleanCalendarEvent("Puasa Asyura",
        color: Colors.teal[400],
        description: 'Hari yang disunatkan berpuasa',
        startTime: DateTime(2022, 8, 8),
        endTime: DateTime(2022, 8, 8),
        isAllDay: true),

    //hari wajib puasa
    NeatCleanCalendarEvent("Puasa Ramadhan",
        color: Colors.lime[400],
        description: 'Hari yang diwajibkan berpuasa',
        startTime: DateTime(2022, 4, 3),
        endTime: DateTime(2022, 5, 1),
        isAllDay: true),

    //puasa hari putih
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 1, 16),
        endTime: DateTime(2022, 1, 18),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 2, 15),
        endTime: DateTime(2022, 2, 17),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 3, 16),
        endTime: DateTime(2022, 3, 18),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 5, 14),
        endTime: DateTime(2022, 5, 16),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 6, 13),
        endTime: DateTime(2022, 6, 15),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 7, 14),
        endTime: DateTime(2022, 7, 15),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 8, 11),
        endTime: DateTime(2022, 8, 13),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 9, 10),
        endTime: DateTime(2022, 9, 12),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 10, 10),
        endTime: DateTime(2022, 10, 12),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 11, 8),
        endTime: DateTime(2022, 11, 10),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Hari Putih',
        color: Colors.indigo[300],
        description: 'Berpuasa pada hari bulan mengambang',
        startTime: DateTime(2022, 12, 8),
        endTime: DateTime(2022, 12, 10),
        isAllDay: true),

    //puasa isnin jan
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 1, 3),
        endTime: DateTime(2022, 1, 3),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 1, 10),
        endTime: DateTime(2022, 1, 10),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 1, 17),
        endTime: DateTime(2022, 1, 17),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 1, 24),
        endTime: DateTime(2022, 1, 24),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 1, 31),
        endTime: DateTime(2022, 1, 31),
        isAllDay: true),

    //puasa khamis jan
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 1, 6),
        endTime: DateTime(2022, 1, 6),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 1, 13),
        endTime: DateTime(2022, 1, 13),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 1, 20),
        endTime: DateTime(2022, 1, 20),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 1, 27),
        endTime: DateTime(2022, 1, 27),
        isAllDay: true),

    //puasa isnin feb
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 2, 7),
        endTime: DateTime(2022, 2, 7),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 2, 14),
        endTime: DateTime(2022, 2, 14),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 2, 21),
        endTime: DateTime(2022, 2, 21),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 2, 28),
        endTime: DateTime(2022, 2, 28),
        isAllDay: true),

    //puasa khamis feb
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 2, 3),
        endTime: DateTime(2022, 2, 3),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 2, 10),
        endTime: DateTime(2022, 2, 10),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 2, 17),
        endTime: DateTime(2022, 2, 17),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 2, 24),
        endTime: DateTime(2022, 2, 24),
        isAllDay: true),

    //puasa isnin mac
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 3, 7),
        endTime: DateTime(2022, 3, 7),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 3, 14),
        endTime: DateTime(2022, 3, 14),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 3, 21),
        endTime: DateTime(2022, 3, 21),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 3, 28),
        endTime: DateTime(2022, 3, 28),
        isAllDay: true),

    //puasa khamis mac
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 3, 3),
        endTime: DateTime(2022, 3, 3),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 3, 10),
        endTime: DateTime(2022, 3, 10),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 3, 17),
        endTime: DateTime(2022, 3, 17),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 3, 24),
        endTime: DateTime(2022, 3, 24),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 3, 31),
        endTime: DateTime(2022, 3, 31),
        isAllDay: true),

    //puasa isnin mei
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 5, 9),
        endTime: DateTime(2022, 5, 9),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 4, 16),
        endTime: DateTime(2022, 4, 16),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 5, 23),
        endTime: DateTime(2022, 5, 23),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 5, 30),
        endTime: DateTime(2022, 5, 30),
        isAllDay: true),

    //puasa khamis mei
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 5, 5),
        endTime: DateTime(2022, 5, 5),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 5, 12),
        endTime: DateTime(2022, 5, 12),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 5, 19),
        endTime: DateTime(2022, 5, 19),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 5, 26),
        endTime: DateTime(2022, 5, 26),
        isAllDay: true),

    //puasa isnin jun
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 6, 6),
        endTime: DateTime(2022, 6, 6),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 6, 13),
        endTime: DateTime(2022, 6, 13),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 6, 20),
        endTime: DateTime(2022, 6, 20),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 6, 27),
        endTime: DateTime(2022, 6, 27),
        isAllDay: true),

    //puasa khamis jun
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 6, 2),
        endTime: DateTime(2022, 6, 2),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 6, 9),
        endTime: DateTime(2022, 6, 9),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 6, 16),
        endTime: DateTime(2022, 6, 16),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 6, 23),
        endTime: DateTime(2022, 6, 23),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 6, 30),
        endTime: DateTime(2022, 6, 30),
        isAllDay: true),

    //puasa isnin julai
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 7, 4),
        endTime: DateTime(2022, 7, 4),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 7, 18),
        endTime: DateTime(2022, 7, 18),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 7, 25),
        endTime: DateTime(2022, 7, 25),
        isAllDay: true),

    //puasa khamis julai
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 7, 7),
        endTime: DateTime(2022, 7, 7),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 7, 14),
        endTime: DateTime(2022, 7, 14),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 7, 21),
        endTime: DateTime(2022, 7, 21),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 7, 28),
        endTime: DateTime(2022, 7, 28),
        isAllDay: true),

    //puasa isnin ogos
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 8, 1),
        endTime: DateTime(2022, 8, 1),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 8, 8),
        endTime: DateTime(2022, 8, 8),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 8, 15),
        endTime: DateTime(2022, 8, 15),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 8, 22),
        endTime: DateTime(2022, 8, 22),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 8, 29),
        endTime: DateTime(2022, 8, 19),
        isAllDay: true),

    //puasa khamis ogos
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 8, 4),
        endTime: DateTime(2022, 8, 4),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 8, 11),
        endTime: DateTime(2022, 8, 11),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 8, 18),
        endTime: DateTime(2022, 8, 18),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 8, 25),
        endTime: DateTime(2022, 8, 25),
        isAllDay: true),

    //puasa isnin sep
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 9, 5),
        endTime: DateTime(2022, 9, 5),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 9, 12),
        endTime: DateTime(2022, 9, 12),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 9, 19),
        endTime: DateTime(2022, 9, 19),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 9, 26),
        endTime: DateTime(2022, 9, 26),
        isAllDay: true),

    //puasa khamis sep
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 9, 1),
        endTime: DateTime(2022, 9, 1),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 9, 8),
        endTime: DateTime(2022, 9, 8),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 9, 15),
        endTime: DateTime(2022, 9, 15),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 9, 22),
        endTime: DateTime(2022, 9, 22),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 9, 29),
        endTime: DateTime(2022, 9, 29),
        isAllDay: true),

    //puasa isnin okt
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 10, 3),
        endTime: DateTime(2022, 10, 3),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 10, 10),
        endTime: DateTime(2022, 10, 10),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 10, 17),
        endTime: DateTime(2022, 10, 17),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 10, 24),
        endTime: DateTime(2022, 10, 24),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 10, 31),
        endTime: DateTime(2022, 10, 31),
        isAllDay: true),

    //puasa khamis okt
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 10, 6),
        endTime: DateTime(2022, 10, 6),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 10, 13),
        endTime: DateTime(2022, 10, 13),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 10, 20),
        endTime: DateTime(2022, 10, 20),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 10, 27),
        endTime: DateTime(2022, 10, 27),
        isAllDay: true),

    //puasa isnin nov
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 11, 7),
        endTime: DateTime(2022, 11, 7),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 11, 14),
        endTime: DateTime(2022, 11, 14),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 11, 21),
        endTime: DateTime(2022, 11, 21),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 11, 28),
        endTime: DateTime(2022, 11, 28),
        isAllDay: true),

    //puasa khamis nov
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 11, 3),
        endTime: DateTime(2022, 11, 3),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 11, 10),
        endTime: DateTime(2022, 11, 10),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 11, 17),
        endTime: DateTime(2022, 11, 17),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 11, 24),
        endTime: DateTime(2022, 11, 24),
        isAllDay: true),

    //puasa isnin dec
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 12, 5),
        endTime: DateTime(2022, 12, 5),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 12, 12),
        endTime: DateTime(2022, 12, 12),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 12, 19),
        endTime: DateTime(2022, 12, 19),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Isnin',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 12, 26),
        endTime: DateTime(2022, 12, 26),
        isAllDay: true),

    //puasa khamis dec
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 12, 1),
        endTime: DateTime(2022, 12, 1),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 12, 8),
        endTime: DateTime(2022, 12, 8),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 12, 15),
        endTime: DateTime(2022, 12, 15),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 12, 22),
        endTime: DateTime(2022, 12, 22),
        isAllDay: true),
    NeatCleanCalendarEvent('Puasa Khamis',
        color: Colors.pink[400],
        description: 'Hari yang disunatkan puasa',
        startTime: DateTime(2022, 12, 29),
        endTime: DateTime(2022, 12, 29),
        isAllDay: true),
  ];
  return eventList;
}
