import '../Locale/locales.dart';
import '../constants/constant.dart';
import 'clean_calendar_event.dart';

List<CleanCalendarEvent> eventLists(context) {
  var locale = AppLocalizations.of(context)!;
  //TODO EVENT LIST
  final eventLists = [
    //sambutan dan perayaan
    CleanCalendarEvent(locale.fitr!,
        color: kPurple,
        startTime: DateTime(2022, 5, 2),
        endTime: DateTime(2022, 5, 2),
        isAllDay: true),
    CleanCalendarEvent(locale.adha!,
        color: kPurple,
        startTime: DateTime(2022, 7, 9),
        endTime: DateTime(2022, 7, 9),
        isAllDay: true),
    CleanCalendarEvent('Maulidur Rasul',
        color: kPurple,
        startTime: DateTime(2022, 10, 9),
        endTime: DateTime(2022, 10, 9),
        isAllDay: true),
    CleanCalendarEvent('Al-Isra’ wal-Mi’raj',
        color: kPurple,
        startTime: DateTime(2022, 3, 1),
        endTime: DateTime(2022, 3, 1),
        isAllDay: true),
    CleanCalendarEvent('Awal Ramadhan',
        color: kPurple,
        startTime: DateTime(2022, 4, 3),
        endTime: DateTime(2022, 4, 3),
        isAllDay: true),
    CleanCalendarEvent('Nuzul Al-Qur’an',
        color: kPurple,
        startTime: DateTime(2022, 4, 19),
        endTime: DateTime(2022, 4, 19),
        isAllDay: true),

    //awal bulan
    CleanCalendarEvent('1 Jumada Al-Akhir',
        color: kOrange,
        startTime: DateTime(2022, 1, 4),
        endTime: DateTime(2022, 1, 4),
        isAllDay: true),
    CleanCalendarEvent('1 Rajab',
        color: kOrange,
        startTime: DateTime(2022, 2, 3),
        endTime: DateTime(2022, 2, 3),
        isAllDay: true),
    CleanCalendarEvent('1 Sha\'aban',
        color: kOrange,
        startTime: DateTime(2022, 3, 4),
        endTime: DateTime(2022, 3, 4),
        isAllDay: true),
    CleanCalendarEvent('1 Dhu Al-Qi\'dah',
        color: kOrange,
        startTime: DateTime(2022, 6, 1),
        endTime: DateTime(2022, 6, 1),
        isAllDay: true),
    CleanCalendarEvent('1 Dhu Al-Hijjah',
        color: kOrange,
        startTime: DateTime(2022, 7, 1),
        endTime: DateTime(2022, 7, 1),
        isAllDay: true),
    CleanCalendarEvent('1 Muharram',
        color: kOrange,
        startTime: DateTime(2022, 7, 30),
        endTime: DateTime(2022, 7, 1),
        isAllDay: true),
    CleanCalendarEvent('1 Safar',
        color: kOrange,
        startTime: DateTime(2022, 8, 29),
        endTime: DateTime(2022, 8, 29),
        isAllDay: true),
    CleanCalendarEvent('1 Rabi\' Al-Awwal',
        color: kOrange,
        startTime: DateTime(2022, 9, 28),
        endTime: DateTime(2022, 9, 28),
        isAllDay: true),
    CleanCalendarEvent('1 Rabi\' Al-Akhir',
        color: kOrange,
        startTime: DateTime(2022, 10, 27),
        endTime: DateTime(2022, 10, 27),
        isAllDay: true),
    CleanCalendarEvent('1 Jumada Al-Awwal',
        color: kOrange,
        startTime: DateTime(2022, 11, 26),
        endTime: DateTime(2022, 11, 26),
        isAllDay: true),
    CleanCalendarEvent('1 Jumada Al-Akhir',
        color: kOrange,
        startTime: DateTime(2022, 12, 25),
        endTime: DateTime(2022, 12, 25),
        isAllDay: true),

    //hari haram puasa
    CleanCalendarEvent('10 Dhu Al-Hijjah',
        color: kRed,
        description: locale.puasaharam!,
        startTime: DateTime(2022, 7, 9),
        endTime: DateTime(2022, 7, 9),
        isAllDay: true),
    CleanCalendarEvent(locale.tasyrik!,
        color: kRed,
        description: locale.puasaharam!,
        startTime: DateTime(2022, 7, 10),
        endTime: DateTime(2022, 7, 12),
        isAllDay: true),
    CleanCalendarEvent('1 Shawwal',
        color: kRed,
        description: locale.puasaharam!,
        startTime: DateTime(2022, 5, 2),
        endTime: DateTime(2022, 5, 2),
        isAllDay: true),

    //hari sunat puasa
    CleanCalendarEvent(locale.arafah!,
        color: kTeal,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 7, 8),
        endTime: DateTime(2022, 7, 8),
        isAllDay: true),
    CleanCalendarEvent("Tasu'a",
        color: kTeal,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 7),
        endTime: DateTime(2022, 8, 7),
        isAllDay: true),
    CleanCalendarEvent(locale.asyura!,
        color: kTeal,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 8),
        endTime: DateTime(2022, 8, 8),
        isAllDay: true),

    //hari wajib puasa
    CleanCalendarEvent("Ramadhan",
        color: kLime,
        description: locale.puasawajib!,
        startTime: DateTime(2022, 4, 3),
        endTime: DateTime(2022, 5, 1),
        isAllDay: true),

    //puasa hari putih
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 16),
        endTime: DateTime(2022, 1, 18),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 2, 15),
        endTime: DateTime(2022, 2, 17),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 16),
        endTime: DateTime(2022, 3, 18),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 5, 14),
        endTime: DateTime(2022, 5, 16),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 13),
        endTime: DateTime(2022, 6, 15),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 7, 14),
        endTime: DateTime(2022, 7, 15),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 11),
        endTime: DateTime(2022, 8, 13),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 10),
        endTime: DateTime(2022, 9, 12),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 10),
        endTime: DateTime(2022, 10, 12),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 11, 8),
        endTime: DateTime(2022, 11, 10),
        isAllDay: true),
    CleanCalendarEvent(locale.hariputih!,
        color: kIndigo,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 8),
        endTime: DateTime(2022, 12, 10),
        isAllDay: true),

    //puasa isnin jan
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 3),
        endTime: DateTime(2022, 1, 3),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 10),
        endTime: DateTime(2022, 1, 10),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 17),
        endTime: DateTime(2022, 1, 17),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 24),
        endTime: DateTime(2022, 1, 24),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 31),
        endTime: DateTime(2022, 1, 31),
        isAllDay: true),

    //puasa khamis jan
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 6),
        endTime: DateTime(2022, 1, 6),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 13),
        endTime: DateTime(2022, 1, 13),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 20),
        endTime: DateTime(2022, 1, 20),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 1, 27),
        endTime: DateTime(2022, 1, 27),
        isAllDay: true),

    //puasa isnin feb
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 2, 7),
        endTime: DateTime(2022, 2, 7),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 2, 14),
        endTime: DateTime(2022, 2, 14),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 2, 21),
        endTime: DateTime(2022, 2, 21),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 2, 28),
        endTime: DateTime(2022, 2, 28),
        isAllDay: true),

    //puasa khamis feb
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 2, 3),
        endTime: DateTime(2022, 2, 3),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 2, 10),
        endTime: DateTime(2022, 2, 10),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 2, 17),
        endTime: DateTime(2022, 2, 17),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 2, 24),
        endTime: DateTime(2022, 2, 24),
        isAllDay: true),

    //puasa isnin mac
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 7),
        endTime: DateTime(2022, 3, 7),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 14),
        endTime: DateTime(2022, 3, 14),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 21),
        endTime: DateTime(2022, 3, 21),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 28),
        endTime: DateTime(2022, 3, 28),
        isAllDay: true),

    //puasa khamis mac
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 3),
        endTime: DateTime(2022, 3, 3),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 10),
        endTime: DateTime(2022, 3, 10),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 17),
        endTime: DateTime(2022, 3, 17),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 24),
        endTime: DateTime(2022, 3, 24),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 3, 31),
        endTime: DateTime(2022, 3, 31),
        isAllDay: true),

    //puasa isnin mei
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 5, 9),
        endTime: DateTime(2022, 5, 9),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 4, 16),
        endTime: DateTime(2022, 4, 16),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 5, 23),
        endTime: DateTime(2022, 5, 23),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 5, 30),
        endTime: DateTime(2022, 5, 30),
        isAllDay: true),

    //puasa khamis mei
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 5, 5),
        endTime: DateTime(2022, 5, 5),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 5, 12),
        endTime: DateTime(2022, 5, 12),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 5, 19),
        endTime: DateTime(2022, 5, 19),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 5, 26),
        endTime: DateTime(2022, 5, 26),
        isAllDay: true),

    //puasa isnin jun
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 6),
        endTime: DateTime(2022, 6, 6),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 13),
        endTime: DateTime(2022, 6, 13),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 20),
        endTime: DateTime(2022, 6, 20),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 27),
        endTime: DateTime(2022, 6, 27),
        isAllDay: true),

    //puasa khamis jun
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 2),
        endTime: DateTime(2022, 6, 2),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 9),
        endTime: DateTime(2022, 6, 9),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 16),
        endTime: DateTime(2022, 6, 16),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 23),
        endTime: DateTime(2022, 6, 23),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 6, 30),
        endTime: DateTime(2022, 6, 30),
        isAllDay: true),

    //puasa isnin julai
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 7, 4),
        endTime: DateTime(2022, 7, 4),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 7, 18),
        endTime: DateTime(2022, 7, 18),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 7, 25),
        endTime: DateTime(2022, 7, 25),
        isAllDay: true),

    //puasa khamis julai
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 7, 7),
        endTime: DateTime(2022, 7, 7),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 7, 14),
        endTime: DateTime(2022, 7, 14),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 7, 21),
        endTime: DateTime(2022, 7, 21),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 7, 28),
        endTime: DateTime(2022, 7, 28),
        isAllDay: true),

    //puasa isnin ogos
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 1),
        endTime: DateTime(2022, 8, 1),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 8),
        endTime: DateTime(2022, 8, 8),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 15),
        endTime: DateTime(2022, 8, 15),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 22),
        endTime: DateTime(2022, 8, 22),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 29),
        endTime: DateTime(2022, 8, 19),
        isAllDay: true),

    //puasa khamis ogos
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 4),
        endTime: DateTime(2022, 8, 4),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 11),
        endTime: DateTime(2022, 8, 11),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 18),
        endTime: DateTime(2022, 8, 18),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 8, 25),
        endTime: DateTime(2022, 8, 25),
        isAllDay: true),

    //puasa isnin sep
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 5),
        endTime: DateTime(2022, 9, 5),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 12),
        endTime: DateTime(2022, 9, 12),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 19),
        endTime: DateTime(2022, 9, 19),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 26),
        endTime: DateTime(2022, 9, 26),
        isAllDay: true),

    //puasa khamis sep
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 1),
        endTime: DateTime(2022, 9, 1),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 8),
        endTime: DateTime(2022, 9, 8),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 15),
        endTime: DateTime(2022, 9, 15),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 22),
        endTime: DateTime(2022, 9, 22),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 9, 29),
        endTime: DateTime(2022, 9, 29),
        isAllDay: true),

    //puasa isnin okt
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 3),
        endTime: DateTime(2022, 10, 3),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 10),
        endTime: DateTime(2022, 10, 10),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 17),
        endTime: DateTime(2022, 10, 17),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 24),
        endTime: DateTime(2022, 10, 24),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 31),
        endTime: DateTime(2022, 10, 31),
        isAllDay: true),

    //puasa khamis okt
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 6),
        endTime: DateTime(2022, 10, 6),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 13),
        endTime: DateTime(2022, 10, 13),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 20),
        endTime: DateTime(2022, 10, 20),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 10, 27),
        endTime: DateTime(2022, 10, 27),
        isAllDay: true),

    //puasa isnin nov
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 11, 7),
        endTime: DateTime(2022, 11, 7),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 11, 14),
        endTime: DateTime(2022, 11, 14),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 11, 21),
        endTime: DateTime(2022, 11, 21),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 11, 28),
        endTime: DateTime(2022, 11, 28),
        isAllDay: true),

    //puasa khamis nov
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 11, 3),
        endTime: DateTime(2022, 11, 3),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 11, 10),
        endTime: DateTime(2022, 11, 10),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 11, 17),
        endTime: DateTime(2022, 11, 17),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 11, 24),
        endTime: DateTime(2022, 11, 24),
        isAllDay: true),

    //puasa isnin dec
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 5),
        endTime: DateTime(2022, 12, 5),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 12),
        endTime: DateTime(2022, 12, 12),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 19),
        endTime: DateTime(2022, 12, 19),
        isAllDay: true),
    CleanCalendarEvent(locale.puasaisnin!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 26),
        endTime: DateTime(2022, 12, 26),
        isAllDay: true),

    //puasa khamis dec
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 1),
        endTime: DateTime(2022, 12, 1),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 8),
        endTime: DateTime(2022, 12, 8),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 15),
        endTime: DateTime(2022, 12, 15),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 22),
        endTime: DateTime(2022, 12, 22),
        isAllDay: true),
    CleanCalendarEvent(locale.puasakhamis!,
        color: kPink,
        description: locale.puasasunat!,
        startTime: DateTime(2022, 12, 29),
        endTime: DateTime(2022, 12, 29),
        isAllDay: true),
  ];
  return eventLists;
}
